---
title: "Seminar 1"
author: "Eric G. E. Nilsen"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Seminar 1

Her har jeg lasta ned en nettside, og lagra den

```{r}
library(tidyverse)
library(stortingscrape) 
library(rvest) 
library(textreadr)


#//*[@id="maincontent"]/div

download.file("https://www.theguardian.com/politics/2003/mar/18/foreignpolicy.iraq1", destfile = "blairIraq.html")


blair_text <- read_html("blairIraq.html") %>% 
  html_nodes(xpath = "//*[@id='maincontent']/div") %>% 
  html_text2()


blair_text <- read_html("https://www.theguardian.com/politics/2003/mar/18/foreignpolicy.iraq1") %>% 
  html_nodes(xpath = "//*[@id='maincontent']/div") %>% 
  html_text2()


saveRDS(blair_text, "sma_filer/sem1blair.rds")
blairnr222222 <- readRDS("sma_filer/sem1blair.rds")

writeLines(blair_text, "textFile.txt")


```

Stortings API

```{r}

spr_time <- stortingscrape::get_question_hour(300)

cat(spr_time$question_time$question_text)
r


noo <- readtext::readtext("Analytisk sammendrag av Kant.docx")
cat(noo$text)
```
